import type { Metadata } from 'next';
import { GeistSans, GeistMono } from 'geist/font';
import { Providers } from '@/components/providers/session-provider';
import './globals.css';

const geistSans = GeistSans;
const geistMono = GeistMono;

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
      style={
        {
          '--geist-sans': 'var(--font-geist-sans)',
          '--geist-mono': 'var(--font-geist-mono)',
        } as React.CSSProperties
      }
    >
      <body className="antialiased">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
